spring:
  application:
    name: AlumniManagement

  datasource:
    password: admin1234
    url: jdbc:postgresql://localhost:5432/almuni-database
    username: postgres

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

        format_sql: true
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 8085

keycloak:
  auth-server-url: http://localhost:8080/auth
  realm: SpringBootKeycloak
  resource: login-app
  public-client: true
  bearer-only: true
